version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - 4873:4873
    volumes:
      - ./conf:/verdaccio/conf
      - ./storage:/verdaccio/storage
      - ./plugins:/verdaccio/plugins
